import { createContext, useContext, useState } from "react";

export type Language = "en" | "fr" | "de" | "ar";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        home: "Home",
        generate: "Generate Letter",
        about: "About",
        contact: "Contact",
        heroTitle: "Craft Perfect Cover Letters",
        heroSubtitle: "AI-powered cover letter generation that makes you stand out. Professional, tailored, and ready in seconds.",
        getStarted: "Get Started",
        learnMore: "Learn More",
        howItWorks: "How It Works",
        step1Title: "Enter Your Details",
        step1Desc: "Share your professional background and the job you're applying for.",
        step2Title: "AI Magic",
        step2Desc: "Our advanced AI analyzes and crafts a personalized cover letter.",
        step3Title: "Download & Apply",
        step3Desc: "Get your polished cover letter ready to send to employers.",
        aboutTitle: "About Letterly",
        aboutText: "Letterly is an AI-powered platform designed to help job seekers create compelling, professional cover letters in seconds. We combine cutting-edge AI technology with proven writing strategies to give you the competitive edge in your job search.",
        contactTitle: "Get in Touch",
        contactText: "Have questions or feedback? We'd love to hear from you.",
        name: "Name",
        email: "Email",
        message: "Message",
        send: "Send Message",
        jobTitle: "Job Title",
        companyName: "Company Name",
        yourExperience: "Your Experience",
        skills: "Key Skills",
        generateLetter: "Generate Cover Letter",
        downloading: "Generating...",
        // New keys
        fullName: "Full Name",
        linkOptional: "Link (Optional)",
        postDescription: "Post Description",
        letterLanguage: "Letter Language",
        selectLanguage: "Select language",
        pasteJobDescription: "Paste the job posting description here...",
        describeExperience: "Describe your relevant work experience...",
        listSkills: "List your key skills...",
        generating: "Generating...",
        generatedLetterHeader: "Generated Letter",
        copy: "Copy",
        download: "Download",
        downloadPDF: "Download as PDF",
        downloadDOCX: "Download as DOCX",
        downloadTXT: "Download as TXT",
        crafting: "Crafting your perfect cover letter...",
        willAppear: "Your generated cover letter will appear here",
        fillDetails: "Fill in the details below to create your perfect cover letter",
        successGenerated: "Cover letter generated successfully!",
        successCopied: "Copied to clipboard!",
        errorFillRequired: "Please fill in all required fields",
        errorGenerationFailed: "Failed to generate cover letter.",
        ourMission: "Our Mission",
        missionDesc: "Empower job seekers with AI technology to create compelling cover letters that get noticed.",
        lightningFast: "Lightning Fast",
        fastDesc: "Generate professional cover letters in seconds, not hours. Save time and apply to more jobs.",
        privacyFirst: "Privacy First",
        privacyDesc: "Your data is secure and private. We never share your information with third parties.",
        whyLetterly: "Why Letterly?",
        whyText1: "In today's competitive job market, a well-crafted cover letter can be the difference between landing an interview and being overlooked. However, writing a compelling cover letter takes time, effort, and expertise.",
        whyText2: "Letterly combines advanced AI technology with proven writing strategies to help you create personalized, professional cover letters in seconds. Our AI analyzes your experience, the job requirements, and industry best practices to generate letters that highlight your unique value proposition.",
        whyText3: "Whether you're a seasoned professional or just starting your career, Letterly gives you the tools to present yourself in the best possible light and increase your chances of landing your dream job.",
        fillAllFields: "Please fill in all fields",
        messageSent: "Message sent successfully!",
        returnHome: "Return to Home",
        pageNotFound: "Page not found",
        oops: "Oops!",
        error404: "404",
    },
    fr: {
        home: "Accueil",
        generate: "Générer une Lettre",
        about: "À Propos",
        contact: "Contact",
        heroTitle: "Créez des Lettres de Motivation Parfaites",
        heroSubtitle: "Génération de lettres de motivation alimentée par l'IA qui vous démarque. Professionnel, personnalisé et prêt en quelques secondes.",
        getStarted: "Commencer",
        learnMore: "En Savoir Plus",
        howItWorks: "Comment Ça Marche",
        step1Title: "Entrez Vos Détails",
        step1Desc: "Partagez votre parcours professionnel et l'emploi pour lequel vous postulez.",
        step2Title: "Magie de l'IA",
        step2Desc: "Notre IA avancée analyse et crée une lettre de motivation personnalisée.",
        step3Title: "Téléchargez et Postulez",
        step3Desc: "Obtenez votre lettre de motivation soignée prête à envoyer aux employeurs.",
        aboutTitle: "À Propos de Letterly",
        aboutText: "Letterly est une plateforme alimentée par l'IA conçue pour aider les chercheurs d'emploi à créer des lettres de motivation convaincantes et professionnelles en quelques secondes.",
        contactTitle: "Contactez-Nous",
        contactText: "Vous avez des questions ou des commentaires? Nous aimerions vous entendre.",
        name: "Nom",
        email: "Email",
        message: "Message",
        send: "Envoyer",
        jobTitle: "Titre du Poste",
        companyName: "Nom de l'Entreprise",
        yourExperience: "Votre Expérience",
        skills: "Compétences Clés",
        generateLetter: "Générer la Lettre",
        downloading: "Génération...",
        // New keys
        fullName: "Nom Complet",
        linkOptional: "Lien (Optionnel)",
        postDescription: "Description du Poste",
        letterLanguage: "Langue de la Lettre",
        selectLanguage: "Sélectionner la langue",
        pasteJobDescription: "Collez la description de l'offre d'emploi ici...",
        describeExperience: "Décrivez votre expérience professionnelle pertinente...",
        listSkills: "Listez vos compétences clés...",
        generating: "Génération...",
        generatedLetterHeader: "Lettre Générée",
        copy: "Copier",
        download: "Télécharger",
        downloadPDF: "Télécharger en PDF",
        downloadDOCX: "Télécharger en DOCX",
        downloadTXT: "Télécharger en TXT",
        crafting: "Création de votre lettre de motivation parfaite...",
        willAppear: "Votre lettre générée apparaîtra ici",
        fillDetails: "Remplissez les détails ci-dessous pour créer votre lettre parfaite",
        successGenerated: "Lettre de motivation générée avec succès !",
        successCopied: "Copié dans le presse-papiers !",
        errorFillRequired: "Veuillez remplir tous les champs obligatoires",
        errorGenerationFailed: "Échec de la génération de la lettre.",
        ourMission: "Notre Mission",
        missionDesc: "Donner aux chercheurs d'emploi la technologie IA pour créer des lettres convaincantes qui se font remarquer.",
        lightningFast: "Éclair",
        fastDesc: "Générez des lettres professionnelles en quelques secondes. Gagnez du temps et postulez à plus d'emplois.",
        privacyFirst: "Confidentialité d'Abord",
        privacyDesc: "Vos données sont sécurisées et privées. Nous ne partageons jamais vos informations.",
        whyLetterly: "Pourquoi Letterly ?",
        whyText1: "Dans le marché du travail concurrentiel d'aujourd'hui, une lettre bien rédigée peut faire la différence. Cependant, écrire une lettre convaincante prend du temps et de l'expertise.",
        whyText2: "Letterly combine une IA avancée avec des stratégies d'écriture éprouvées pour vous aider à créer des lettres personnalisées en quelques secondes.",
        whyText3: "Que vous soyez un professionnel chevronné ou débutant, Letterly vous donne les outils pour vous présenter sous votre meilleur jour.",
        fillAllFields: "Veuillez remplir tous les champs",
        messageSent: "Message envoyé avec succès !",
        returnHome: "Retour à l'Accueil",
        pageNotFound: "Page non trouvée",
        oops: "Oups !",
        error404: "404",
    },
    de: {
        home: "Startseite",
        generate: "Brief Erstellen",
        about: "Über Uns",
        contact: "Kontakt",
        heroTitle: "Perfekte Bewerbungsschreiben Erstellen",
        heroSubtitle: "KI-gestützte Erstellung von Bewerbungsschreiben, die Sie hervorheben. Professionell, maßgeschneidert und in Sekunden fertig.",
        getStarted: "Loslegen",
        learnMore: "Mehr Erfahren",
        howItWorks: "Wie Es Funktioniert",
        step1Title: "Details Eingeben",
        step1Desc: "Teilen Sie Ihren beruflichen Hintergrund und die Stelle, auf die Sie sich bewerben.",
        step2Title: "KI-Magie",
        step2Desc: "Unsere fortschrittliche KI analysiert und erstellt ein personalisiertes Bewerbungsschreiben.",
        step3Title: "Herunterladen & Bewerben",
        step3Desc: "Erhalten Sie Ihr ausgefeiltes Bewerbungsschreiben bereit zum Versenden.",
        aboutTitle: "Über Letterly",
        aboutText: "Letterly ist eine KI-gestützte Plattform, die Arbeitssuchenden hilft, überzeugende, professionelle Bewerbungsschreiben in Sekunden zu erstellen.",
        contactTitle: "Kontaktieren Sie Uns",
        contactText: "Haben Sie Fragen oder Feedback? Wir würden gerne von Ihnen hören.",
        name: "Name",
        email: "E-Mail",
        message: "Nachricht",
        send: "Nachricht Senden",
        jobTitle: "Berufsbezeichnung",
        companyName: "Firmenname",
        yourExperience: "Ihre Erfahrung",
        skills: "Wichtige Fähigkeiten",
        generateLetter: "Brief Generieren",
        downloading: "Wird Generiert...",
        // New keys
        fullName: "Vollständiger Name",
        linkOptional: "Link (Optional)",
        postDescription: "Stellenbeschreibung",
        letterLanguage: "Sprache des Briefs",
        selectLanguage: "Sprache auswählen",
        pasteJobDescription: "Fügen Sie hier die Stellenbeschreibung ein...",
        describeExperience: "Beschreiben Sie Ihre relevante Berufserfahrung...",
        listSkills: "Listen Sie Ihre wichtigsten Fähigkeiten auf...",
        generating: "Generiere...",
        generatedLetterHeader: "Generierter Brief",
        copy: "Kopieren",
        download: "Herunterladen",
        downloadPDF: "Als PDF herunterladen",
        downloadDOCX: "Als DOCX herunterladen",
        downloadTXT: "Als TXT herunterladen",
        crafting: "Erstelle Ihr perfektes Bewerbungsschreiben...",
        willAppear: "Ihr generierter Brief erscheint hier",
        fillDetails: "Füllen Sie die Details unten aus, um Ihren perfekten Brief zu erstellen",
        successGenerated: "Bewerbungsschreiben erfolgreich generiert!",
        successCopied: "In die Zwischenablage kopiert!",
        errorFillRequired: "Bitte füllen Sie alle Pflichtfelder aus",
        errorGenerationFailed: "Fehler beim Generieren des Briefs.",
        ourMission: "Unsere Mission",
        missionDesc: "Arbeitssuchende mit KI-Technologie befähigen, überzeugende Bewerbungsschreiben zu erstellen.",
        lightningFast: "Blitzschnell",
        fastDesc: "Erstellen Sie professionelle Briefe in Sekunden. Sparen Sie Zeit und bewerben Sie sich auf mehr Stellen.",
        privacyFirst: "Datenschutz Zuerst",
        privacyDesc: "Ihre Daten sind sicher und privat. Wir geben Ihre Informationen niemals weiter.",
        whyLetterly: "Warum Letterly?",
        whyText1: "Im heutigen wettbewerbsintensiven Arbeitsmarkt kann ein gut geschriebener Brief den Unterschied machen. Das Schreiben erfordert jedoch Zeit und Fachwissen.",
        whyText2: "Letterly kombiniert fortschrittliche KI mit bewährten Schreibstrategien, um Ihnen zu helfen, personalisierte Briefe in Sekunden zu erstellen.",
        whyText3: "Egal, ob Sie ein erfahrener Profi oder Berufseinsteiger sind, Letterly gibt Ihnen die Werkzeuge, um sich bestmöglich zu präsentieren.",
        fillAllFields: "Bitte füllen Sie alle Felder aus",
        messageSent: "Nachricht erfolgreich gesendet!",
        returnHome: "Zurück zur Startseite",
        pageNotFound: "Seite nicht gefunden",
        oops: "Hoppla!",
        error404: "404",
    },
    ar: {
        home: "الرئيسية",
        generate: "إنشاء خطاب",
        about: "عن المنصة",
        contact: "اتصل بنا",
        heroTitle: "اصنع خطابات تقديم مثالية",
        heroSubtitle: "إنشاء خطابات تقديم بالذكاء الاصطناعي تجعلك متميزاً. احترافي، مخصص، وجاهز في ثوانٍ.",
        getStarted: "ابدأ الآن",
        learnMore: "اعرف المزيد",
        howItWorks: "كيف يعمل",
        step1Title: "أدخل تفاصيلك",
        step1Desc: "شارك خلفيتك المهنية والوظيفة التي تتقدم لها.",
        step2Title: "سحر الذكاء الاصطناعي",
        step2Desc: "يقوم الذكاء الاصطناعي المتقدم بتحليل وصياغة خطاب تقديم مخصص.",
        step3Title: "حمّل وتقدّم",
        step3Desc: "احصل على خطاب التقديم المصقول جاهزاً للإرسال.",
        aboutTitle: "عن ليترلي",
        aboutText: "ليترلي هي منصة مدعومة بالذكاء الاصطناعي مصممة لمساعدة الباحثين عن عمل على إنشاء خطابات تقديم مقنعة واحترافية في ثوانٍ.",
        contactTitle: "تواصل معنا",
        contactText: "هل لديك أسئلة أو ملاحظات؟ نود أن نسمع منك.",
        name: "الاسم",
        email: "البريد الإلكتروني",
        message: "الرسالة",
        send: "إرسال",
        jobTitle: "المسمى الوظيفي",
        companyName: "اسم الشركة",
        yourExperience: "خبرتك",
        skills: "المهارات الأساسية",
        generateLetter: "إنشاء الخطاب",
        downloading: "جارٍ الإنشاء...",
        // New keys
        fullName: "الاسم الكامل",
        linkOptional: "رابط (اختياري)",
        postDescription: "وصف الوظيفة",
        letterLanguage: "لغة الخطاب",
        selectLanguage: "اختر اللغة",
        pasteJobDescription: "الصق وصف الوظيفة هنا...",
        describeExperience: "صف خبرتك العملية ذات الصلة...",
        listSkills: "اذكر مهاراتك الأساسية...",
        generating: "جارٍ الإنشاء...",
        generatedLetterHeader: "الخطاب المُنشأ",
        copy: "نسخ",
        download: "تحميل",
        downloadPDF: "تحميل كـ PDF",
        downloadDOCX: "تحميل كـ DOCX",
        downloadTXT: "تحميل كـ TXT",
        crafting: "جاري صياغة خطاب التقديم المثالي...",
        willAppear: "سيظهر خطابك المُنشأ هنا",
        fillDetails: "املأ التفاصيل أدناه لإنشاء خطابك المثالي",
        successGenerated: "تم إنشاء خطاب التقديم بنجاح!",
        successCopied: "تم النسخ إلى الحافظة!",
        errorFillRequired: "يرجى ملء جميع الحقول المطلوبة",
        errorGenerationFailed: "فشل في إنشاء خطاب التقديم.",
        ourMission: "مهمتنا",
        missionDesc: "تمكين الباحثين عن عمل بتقنية الذكاء الاصطناعي لإنشاء خطابات مقنعة تلفت الانتباه.",
        lightningFast: "سريع جداً",
        fastDesc: "أنشئ خطابات احترافية في ثوانٍ. وفر الوقت وتقدم لمزيد من الوظائف.",
        privacyFirst: "الخصوصية أولاً",
        privacyDesc: "بياناتك آمنة وخاصة. نحن لا نشارك معلوماتك أبداً.",
        whyLetterly: "لماذا ليترلي؟",
        whyText1: "في سوق العمل التنافسي اليوم، يمكن لخطاب مكتوب جيداً أن يحدث الفرق. ومع ذلك، فإن كتابة خطاب مقنع تستغرق وقتاً وخبرة.",
        whyText2: "تجمع ليترلي بين الذكاء الاصطناعي المتقدم واستراتيجيات الكتابة المثبتة لمساعدتك في إنشاء خطابات مخصصة في ثوانٍ.",
        whyText3: "سواء كنت محترفاً متمرساً أو تبدأ مسيرتك المهنية، تمنحك ليترلي الأدوات لتقديم نفسك بأفضل صورة ممكنة.",
        fillAllFields: "يرجى ملء جميع الحقول",
        messageSent: "تم إرسال الرسالة بنجاح!",
        returnHome: "العودة للرئيسية",
        pageNotFound: "الصفحة غير موجودة",
        oops: "عفواً!",
        error404: "404",
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguage] = useState<Language>("en");

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within LanguageProvider");
    }
    return context;
};
